-- Script para criação da estrutura simples do banco de dados Comercial.fdb
-- Compatível com Delphi 10.1 e Firebird 4.0
-- Versão: 1.0
-- Autor: Iago Renan

-- Criação do gerador (sequence) para auto-incremento
CREATE SEQUENCE GEN_CLIENTE_ID;

-- Tabela de Clientes
CREATE TABLE CLIENTES (
    ID_CLIENTE INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF_CNPJ VARCHAR(20),
    TIPO CHAR(1) DEFAULT 'F' NOT NULL, -- F=Física, J=Jurídica
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(100),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    UF CHAR(2),
    CEP VARCHAR(10),
    ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,
    OBSERVACOES BLOB SUB_TYPE TEXT,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT CHK_CLIENTES_TIPO CHECK (TIPO IN ('F', 'J')),
    CONSTRAINT CHK_CLIENTES_ATIVO CHECK (ATIVO IN ('S', 'N'))
);

-- Criação de um índice para o campo CPF_CNPJ
CREATE INDEX IDX_CLIENTES_CPF_CNPJ ON CLIENTES (CPF_CNPJ);

-- Criação da trigger para auto-incremento do ID_CLIENTE
CREATE OR ALTER TRIGGER TRG_CLIENTES_BI FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_CLIENTE IS NULL) THEN
    NEW.ID_CLIENTE = NEXT VALUE FOR GEN_CLIENTE_ID;
END;

-- Trigger para atualizar a data de atualização
CREATE OR ALTER TRIGGER TRG_CLIENTES_BU FOR CLIENTES
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  NEW.DATA_ATUALIZACAO = CURRENT_TIMESTAMP;
END;

COMMIT WORK;